Auto refresh view
digitallyinduced/ihp pull request #419
Opened 2020-09-24 06:16 UTC by mpscholten

https://twitter.com/digitallyinduce/status/1308678484735283200

Open tasks:
- [ ] Remove hard coded table names
- [ ] Only send view when it actually changed
- [ ] Documentation

2020-09-30 14:16 UTC, mpscholten commented
@HugoPeters1024  maybe you could also take a look over this :) ?

2020-09-30 14:49 UTC, HugoPeters1024 commented
@mpscholten I didn't know up until this moment that postgres could do this (very cool indeed!) and find it hard to reason about the implementation. However, I will certain try to make an MVP using this functionality and let know you if it worked.

2020-09-30 14:58 UTC, mpscholten commented
Thanks for the fast response. Cool, this is also a good for the documentation I guess :)

2020-10-01 11:59 UTC, Laobiz requested changes
Great work 👍 At the moment there is no delete trigger for the tables. It would make sense to also auto reload when a deletion happened.

2020-10-01 16:21 UTC, HugoPeters1024 commented on Guide/auto-refresh.markdown
> +Whenenver a `INSERT` or `UPDATE` happens to the tables used by your action IHP will rerun your action on the serverside. When the generated html looks different to the html generated on the initial p
I saw delete has now also been added :)

2020-10-01 16:32 UTC, mpscholten commented on lib/IHP/static/ihp-auto-refresh.js
> +    var socketHost = "ws://" + window.location.hostname + ":" + document.location.port;
Yes that actually happend when we deployed it the first time to IHP cloud :D That was then fixed in a later commit via https://github.com/digitallyinduced/ihp/pull/419/commits/4cec09d8d59b612ebe592d54a1b28ead40692fff

2020-10-01 16:33 UTC, mpscholten commented on Guide/auto-refresh.markdown
> +Whenenver a `INSERT` or `UPDATE` happens to the tables used by your action IHP will rerun your action on the serverside. When the generated html looks different to the html generated on the initial p
Good catch :) Fixed 👍

2020-10-01 16:58 UTC, mpscholten commented on Guide/auto-refresh.markdown
> +instance InitControllerContext WebApplication where
Good point, just changed it 👍

2020-10-01 17:56 UTC, merged